package Feb13;

public class ThreadDemo {
    public static void main(String[] args) {
        Thread thrd = new Thread(() -> {
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
            System.out.println("HIIII");
            System.out.println("HALOO");
        });
        thrd.start();
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
        System.out.println("Thread has started");
    }
}
